### PR TITLE
Fallback to ANSII codes if tput fails

### PR DESCRIPTION
**Pull request by hrefhref**
### Summary of changes

On FreeBSD, tput is using termcap instead of terminfo -- so the codes are not the same. Also it seems that termcap don't have codes for colors.

This fixes uses ANSII codes when tput fails.

### CODE REVIEW

**Comment by OvermindDL1** [comment]
> On FreeBSD, tput is using termcap instead of terminfo -- so the codes are not the same. Also it seems that termcap don't have codes for colors.

Wait what?  Back on FreeBSD 4 I used `tput` excessively for getting color codes, is that broken on modern systems?!  o.O

**Comment by hrefhref** [comment]
@OvermindDL1 Oh? Interesting! How are you doing it ?

`setaf` and `setf` don't work for me. Maybe you used the port's/ncurses's tput, and not the system one?

**Comment by OvermindDL1** [comment]
@hrefhref Funny enough I still have my meta-library script from those old days (ahhh ksh88, those days sucked ^.^).  Unsure what version of tput though, but here is a snippet from that *monstrous* library script:
```sh
        typeset RES BLUE WHITE RED GREEN YELLOW 
        RES=`tput rmso`
        BLUE=`tput bold``tput setf 6`
        WHITE=`tput bold``tput setf 7`
        RED=`tput bold``tput setf 1`
        GREEN=`tput bold``tput setf 2`
        YELLOW=`tput bold``tput setf 3`
```

I do remember a lot of things did not match the documentation, like at all, but a lot of testing back and forth got it all figured out on that old system.

**Comment by hrefhref** [comment]
@OvermindDL1 I think you were using the port's tput and not the system one then :) All of theses are failing with system's tput:

```
@ummagumma ~ $ tput rmso
@ummagumma ~ $ echo $?
1

@ummagumma ~ $ tput setf 6
@ummagumma ~ $ echo $?
1

@ummagumma ~ $ tput bold
@ummagumma ~ $ echo $?
1
```

**Comment by OvermindDL1** [comment]
Could make the fixed `tput` a requirement then otherwise no coloring?  ^.^

**Comment by hrefhref** [comment]
I don't like the idea of having another dependency. Falling back to ANSII codes seems the correct way to do it.

And if you have the correct tput, it'll work anyway!

**Comment by deadtrickster** [comment]
please merge it already

**Comment by deadtrickster** [comment]
Hope this will be pushed to hex soon :-). Thanks

**Pull request merged**
