### PR TITLE
Validation of include_erts

### PR DESCRIPTION
**Pull request by mariosangiorgio**
Moved validation of `include_erts` to `apply_configuration` so Distillery first checks that everything is in place and then starts creating the release.

I tried to make the returned error as informative as possible and to write idiomatic Elixir. Since I am still an Elixir beginner I might have failed. Feel free to review this pull request and to ask to change whatever it needs to be changed to improve the code.

### CODE REVIEW

**Comment by bitwalker** [comment]
Just a couple of fixes and I'll get this merged :)

**Comment by bitwalker** [comment]
ping ;)

**Comment by mariosangiorgio** [comment]
I'm here :)

What does need to be fixed? I'm happy to go on and do it

**Comment by bitwalker** [comment]
@mariosangiorgio Sorry, the code review stuff was in pending state, not submitted, so it wasn't showing up. My bad :(

**Comment by mariosangiorgio** [comment]
The `git rebase master include_erts_validation` I did didn't work as I expected so I messed up a bit this branch. Let me know if you want me to create a new pull request on a clean branch.

The new changes are b10eded and 4924190.

I verified that this works, but I had to (locally) unpick a613d2ed164c3cc829a16fcc9bc5ca2d23460a75. See the comment I left there.

**Comment by bitwalker** [comment]
Just FYI, I usually just do `git rebase master` from whatever branch I'm working on (after I've already done `git pull origin master` on the master branch to ensure it's up to date). So far I haven't had any problems, but I may have been lucky. Worth a shot next time anyway!

I'll manually tease apart the commits.

**Comment by bitwalker** [comment]
@mariosangiorgio Ok, I *think* I got the correct changes merged. Please take a look when you get a chance and let me know if anything got missed!

**Comment by mariosangiorgio** [comment]
Looks good to me

**Pull request closed without merging**
