### PR TITLE
Allow migrations by Repo

### PR DESCRIPTION
**Pull request by nardopessoa**
The "repo" name was fixed in sample code. I just put it dynamically using `Mix.Ecto` module.

### CODE REVIEW

**Comment by michalmuskala** [comment]
The `Mix.Ecto` module is not public.

**Comment by bitwalker** [comment]
Unfortunately, if `Mix.Ecto` is not public, I won't merge this, as it could cause problems if that module goes away or changes. Was there a specific problem with the old migrator example?

**Comment by nardopessoa** [comment]
Well, the string "repo" used in example is a reference for Repo module name.
My Repo name is AppRepo and the folder for yours migrations is "priv/app_repo/migrations" (generated by Ecto.Gen.Migration).
When I run the example code, the folder "repo" never was found.
I fix this with this pull request codes... but... it's not ok... =(

**Comment by bitwalker** [comment]
@nardopessoa If you submit a PR which passes both the app name and repo name to the affected functions, we should only need to change the use of `"repo"` to `Macro.underscore(repo)`.

**Comment by nardopessoa** [comment]
@bitwalker, I fix the code using your sugestion: `Macro.underscore(repo)`.
I hope everything is right now.

**Comment by bitwalker** [comment]
Thanks!

**Pull request merged**
