### PR TITLE
Update Running Migrations.md

### PR DESCRIPTION
**Pull request by arcz**
### Summary of changes

Unused var, should be passed to `:code.priv_dir`.

### Checklist

- [x] New functions have typespecs, changed functions were updated
- [x] Same for documentation, including moduledocs
- [x] Tests were added or updated to cover changes
- [x] Commits were squashed into a single coherent commit

### CODE REVIEW

**Comment by marcelfahle** [comment]
Hey!

Where exactly is `:code` coming from? I have a similar set up for my migrations but that wouldn't do it for me and I had to get my priv older from `Application.app_dir`. It's probably just lack of experience but I just don't get it. I hope asking here is ok :-)

**Comment by bitwalker** [comment]
It's provided as part of Erlang, in it's `kernel` application. Are you saying it didn't work? What was the error?

**Comment by marcelfahle** [comment]
Snippet below..
I didn't get the whole `Protocol.UndefinedError` at first, but then I saw that there was a problem with the string coming out of the `priv_dir` helper function, as far as I can tell. 
I put `Application.app_dir(:pidro_admin, "priv")` in place instead and it worked great.

It's probably just some dumb mistake on my end... 

`
{"init terminating in do_boot",
  {# 
    {'__exception__'=>true,'__struct__'=>'Elixir.Protocol.UndefinedError',description=><<>>,protocol=>'Elixir.String.Chars',value=>{error,bad_name}},
    [
      {'Elixir.String.Chars','impl_for!',1,
        [
          {file,"lib/string/chars.ex"},
          {line,3}
        ]
      },
      {'Elixir.String.Chars',to_string,1,
        [
          {file,"lib/string/chars.ex"},
          {line,17}
        ]
      },
      {'Elixir.PidroAdmin.ReleaseTasks',priv_dir,1,
        [
          {file,"lib/release_tasks.ex"},
          {line,40}
        ]
      },
      {'Elixir.PidroAdmin.ReleaseTasks',migrations_path,1,
        [
          {file,"lib/release_tasks.ex"},
          {line,47}
        ]
      },
      {'Elixir.PidroAdmin.ReleaseTasks',run_migrations_for,1,
        [
          {file,"lib/release_tasks.ex"},
          {line,44}
        ]
      },
      {'Elixir.Enum','-each/2-lists^foreach/1-0-',2,
        [
          {file,"lib/enum.ex"},
          {line,645}
        ]
      },
      {'Elixir.Enum',each,2,
        [
          {file,"lib/enum.ex"},
          {line,645}
        ]
      },
      {'Elixir.PidroAdmin.ReleaseTasks',seed,0,
        [
          {file,"lib/release_tasks.ex"},{line,26}
        ]
      }
    ]
  }
}
init terminating in do_boot ()`

**Comment by bitwalker** [comment]
`:code.priv_dir(:someapp)` returns a charlist (Erlang string), rather than a binary (Elixir string), so you have to make sure to convert it to a binary if you are passing it to an Elixir function which expects a binary.

**Comment by marcelfahle** [comment]
Ah, makes sense.. I figured the string interpolation `def priv_dir(app), do: "#{:code.priv_dir(app)}"` would take care of that. Still all a pretty wild new world to me :-)  Thanks man, sorry for bothering with this, and great work on Distillery!

**Comment by bitwalker** [comment]
It does for sure. Are you sure the application name being passed to `priv_dir` is actually an application? If not, it returns something like `{:error, :bad_name}`.

**Comment by marcelfahle** [comment]
Aha!
Turns out the hexdocs still had the old line `Enum.each(@repos, &run_migrations_for/1)` in there, which I just saw has been fixed yesterday, #225 .

**Pull request merged**
