### PR TITLE
`SIG` prefix does not work in `sh`

### PR DESCRIPTION
**Pull request by vishnevskiy**
As the title says.

This trap does did not work in sh.

### CODE REVIEW

**Comment by brainlid** [comment]
Verified to fix issue #18.

**Comment by merqlove** [comment]
Yeah, it works

**Comment by shanesveller** [comment]
I posted a workaround for Debian/Ubuntu users in the comments on #18, which doesn't require a change to Distillery itself.

**Comment by brainlid** [comment]
Thanks @shanesveller, verified that change works. Added it to my docker file used for deploying the release as follows:

```text
RUN echo 'dash dash/sh boolean false' | debconf-set-selections
RUN dpkg-reconfigure -phigh dash
```

**Comment by bitwalker** [comment]
I'm going to document the fix from #18 rather than merge this. Thanks for the PR though!

**Pull request closed without merging**
