### PR TITLE
Add pre_upgrade/post_upgrade hooks

### PR DESCRIPTION
**Pull request by spscream**
I added pre_upgrade/post_upgrade hooks configuration and overlays, but I'm not sure if this is a right place to execute them. @bitwalker is it correct?

### CODE REVIEW

**Comment by bitwalker** [comment]
Looks correct to me, but could you also update the docs to reflect the new configuration options?

**Comment by bitwalker** [comment]
@spscream ping :)

See #92 (ignore this, just want to link this PR to the original issue)

**Comment by spscream** [comment]
@bitwalker ok, I'll add the documentation next week, I'm little busy right now.

**Comment by bitwalker** [comment]
@spscream No worries, I can take care of it :)

**Pull request merged**
